# Generated by Django 2.0.2 on 2018-02-13 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sku",
            name="variant",
            field=models.ForeignKey(
                default="UNK",
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="product.Size",
            ),
        ),
    ]
