# Generated by Django 2.0.2 on 2018-02-19 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remittance_doc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='remittanceitem',
            name='orig_file',
            field=models.FileField(null=True, upload_to='error'),
        ),
    ]
