# Generated by Django 2.0.2 on 2018-02-15 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RemittanceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(default='Start', max_length=15, verbose_name='Remittance State')),
                ('orig_name', models.CharField(max_length=255)),
                ('source_doc', models.FilePathField(max_length=255, verbose_name='Source Doc')),
                ('yaml_doc', models.CharField(max_length=255, verbose_name='Yaml Doc')),
            ],
        ),
    ]
