# Generated by Django 2.0.2 on 2018-02-19 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remittance', '0002_remittanceitem_orig_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remittanceitem',
            name='orig_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='remittanceitem',
            name='source_doc',
            field=models.FilePathField(max_length=255, null=True, verbose_name='Source Doc'),
        ),
        migrations.AlterField(
            model_name='remittanceitem',
            name='yaml_doc',
            field=models.CharField(default='', max_length=255, verbose_name='Yaml Doc'),
        ),
    ]
