# Generated by Django 2.0.2 on 2018-02-28 11:23

from django.db import migrations, models
import django.utils.timezone
import remittance.models


class Migration(migrations.Migration):

    dependencies = [
        ('remittance', '0003_auto_20180219_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='remittanceitem',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='remittanceitem',
            name='orig_file',
            field=models.FileField(null=True, upload_to=remittance.models.remittance_directory_path),
        ),
    ]
