# Generated by Django 2.0.2 on 2018-02-15 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AccrualsTable",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "expense_nc",
                    models.CharField(
                        blank=True, default="", max_length=4, verbose_name="Expense NC"
                    ),
                ),
                (
                    "accruals_nc",
                    models.CharField(max_length=4, verbose_name="Accruals NC"),
                ),
                ("comment", models.CharField(max_length=255, verbose_name="Comment")),
            ],
        ),
    ]
