# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-05 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("xeroapp", "0003_auto_20170917_2146"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="email_address",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Account number"
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Account number"
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Account number"
            ),
        ),
    ]
