# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-04 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sereports", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="parameters",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="URL Parameters"
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="report_number",
            field=models.IntegerField(verbose_name="Report number"),
        ),
    ]
