# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-17 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sereports", "0003_filebabyfile"),
    ]

    operations = [
        migrations.CreateModel(
            name="RemittanceFile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("f", models.FileField(upload_to="/Remittance/")),
                ("md5", models.CharField(max_length=32)),
            ],
        ),
    ]
