# Generated by Django 2.0.2 on 2018-02-13 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sereports", "0004_remittancefile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="remittancefile",
            name="f",
            field=models.FileField(upload_to="Remittance/"),
        ),
    ]
