# Generated by Django 2.0.2 on 2019-09-23 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sereports', '0005_auto_20180213_1539'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Companies'},
        ),
    ]
