# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-22 15:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('xeroId', models.CharField(blank=True, max_length=255, primary_key=True, serialize=False, verbose_name='Xero ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Name of Contact')),
                ('number', models.CharField(blank=True, max_length=50, verbose_name='Account number')),
            ],
        ),
        migrations.CreateModel(
            name='ContactGroup',
            fields=[
                ('xeroId', models.CharField(blank=True, max_length=255, primary_key=True, serialize=False, verbose_name='Xero ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Name of ContactGroup')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('xeroId', models.CharField(blank=True, max_length=255, primary_key=True, serialize=False, verbose_name='Xero ID')),
                ('code', models.CharField(blank=True, max_length=255, verbose_name='Item Code')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Item Name')),
                ('cost_price', models.DecimalField(decimal_places=4, max_digits=16, verbose_name='Cost Price')),
                ('sales_price', models.DecimalField(decimal_places=4, max_digits=16, verbose_name='Cost Price')),
                ('contact_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xero.Contact')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('xeroId', models.CharField(blank=True, max_length=255, primary_key=True, serialize=False, verbose_name='Xero ID')),
                ('code', models.CharField(blank=True, max_length=255, verbose_name='Item Code')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Item Name')),
                ('cost_price', models.DecimalField(decimal_places=4, max_digits=16, verbose_name='Cost Price')),
                ('sales_price', models.DecimalField(decimal_places=4, max_digits=16, verbose_name='Sales Price')),
            ],
        ),
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=16, verbose_name='Qty')),
                ('price', models.DecimalField(decimal_places=4, max_digits=16, verbose_name='Price')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xero.Invoice')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xero.Item')),
            ],
        ),
    ]
