# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-16 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Name of ContactGroup')),
                ('xero_id', models.CharField(blank=True, max_length=255, verbose_name='')),
            ],
        ),
    ]
