# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-22 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xero', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xero_id', models.CharField(blank=True, max_length=255, verbose_name='')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Name of Contact')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xero_id', models.CharField(blank=True, max_length=255, verbose_name='')),
                ('code', models.CharField(blank=True, max_length=255, verbose_name='Item Code')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Item Name')),
                ('cost_price', models.DecimalField(decimal_places=4, max_digits=16, verbose_name='Cost Price')),
                ('sales_price', models.DecimalField(decimal_places=4, max_digits=16, verbose_name='Cost Price')),
            ],
        ),
    ]
