# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-23 14:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('xero', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='code',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='cost_price',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='name',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='sales_price',
        ),
        migrations.AddField(
            model_name='invoice',
            name='currency_code',
            field=models.CharField(blank=True, max_length=3, verbose_name='Currency Code'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='currency_rate',
            field=models.DecimalField(blank=True, decimal_places=8, default=0, max_digits=16, verbose_name='CurrencyRate'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='gross',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Gross'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Invoice Type'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='nett',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Nett'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Tax'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='updated_date_utc',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='UpdatedDateUTC'),
        ),
    ]
