# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-26 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xero', '0002_auto_20170623_1523'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='xeroId',
            new_name='xerodb_id',
        ),
        migrations.RenameField(
            model_name='contactgroup',
            old_name='xeroId',
            new_name='xerodb_id',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='date',
            new_name='inv_date',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='xeroId',
            new_name='xerodb_id',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='xeroId',
            new_name='xerodb_id',
        ),
        migrations.AddField(
            model_name='invoice',
            name='inv_number',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Status'),
        ),
    ]
