# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-22 15:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xero', '0002_contact_inventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('xeroId', models.CharField(blank=True, max_length=255, primary_key=True, serialize=False, verbose_name='Xero ID')),
                ('code', models.CharField(blank=True, max_length=255, verbose_name='Item Code')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Item Name')),
                ('cost_price', models.DecimalField(decimal_places=4, max_digits=16, verbose_name='Cost Price')),
                ('sales_price', models.DecimalField(decimal_places=4, max_digits=16, verbose_name='Cost Price')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('xeroId', models.CharField(blank=True, max_length=255, primary_key=True, serialize=False, verbose_name='Xero ID')),
                ('code', models.CharField(blank=True, max_length=255, verbose_name='Item Code')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Item Name')),
                ('cost_price', models.DecimalField(decimal_places=4, max_digits=16, verbose_name='Cost Price')),
                ('sales_price', models.DecimalField(decimal_places=4, max_digits=16, verbose_name='Cost Price')),
            ],
        ),
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=16, verbose_name='Qty')),
                ('price', models.DecimalField(decimal_places=4, max_digits=16, verbose_name='Price')),
                ('code', models.CharField(blank=True, max_length=255, verbose_name='Item Code')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Item Name')),
                ('cost_price', models.DecimalField(decimal_places=4, max_digits=16, verbose_name='Cost Price')),
                ('sales_price', models.DecimalField(decimal_places=4, max_digits=16, verbose_name='Cost Price')),
                ('invoice_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xero.Invoice')),
                ('items_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xero.Item')),
            ],
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='id',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='xero_id',
        ),
        migrations.RemoveField(
            model_name='contactgroup',
            name='id',
        ),
        migrations.RemoveField(
            model_name='contactgroup',
            name='xero_id',
        ),
        migrations.AddField(
            model_name='contact',
            name='number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Account number'),
        ),
        migrations.AddField(
            model_name='contact',
            name='xeroId',
            field=models.CharField(blank=True, max_length=255, primary_key=True, serialize=False, verbose_name='Xero ID'),
        ),
        migrations.AddField(
            model_name='contactgroup',
            name='xeroId',
            field=models.CharField(blank=True, max_length=255, primary_key=True, serialize=False, verbose_name='Xero ID'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='contact_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xero.Contact'),
        ),
    ]
