# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-27 13:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xero', '0003_auto_20170626_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='contact_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xero.Contact'),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xero.Item'),
        ),
    ]
